# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cb3f54e942854925dda797ed442536ad2062a01479108e4c4c803c11417e86339763fbbef335b022451f436987aeb70dd12cf30d68349aa7c29e93fa67c7717

test:
  secret_key_base: b1c59933f77f9d4d9b81e15e63a29beafcdb5b78dc35826363a38970d7081acb7d9ba0322595ad1799e506add6595fb5e7aa804e614b7b194f1c4a6b98ec0367

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
